'use client'

import { useRouter } from 'next/navigation'
import { useAuth } from '../../Lib/auth'
import { useState } from 'react'

export default function Resources() {
  const { user } = useAuth()
  const router = useRouter()
  const [suggestionForm, setSuggestionForm] = useState({
    name: '',
    email: '',
    resourceName: '',
    resourceUrl: '',
    description: '',
    category: ''
  })
  const [submitted, setSubmitted] = useState(false)

  const handlePrint = () => {
    window.print()
  }

  const handleDownload = () => {
    const resourceContent = `
CompSherpa Resource Library
===========================

Job Negotiation Resource Library for Nurse Practitioners & Medical Professionals

QUICK TIPS FROM SOURCE LIBRARY
For nurse practitioners and medical job seekers, maximizing career success goes far beyond base salary. The most effective professionals:

• Use trusted sources to benchmark compensation and understand regional/specialty trends.
• Proactively prepare for negotiations, focusing on total compensation—not just salary. This includes bonuses, paid leave, CME, retirement, flexible scheduling, and student loan support.
• Rely on peer-reviewed guides, podcasts, and real contract checklists to avoid overlooked pitfalls.
• Join professional organizations for member-exclusive salary data, toolkits, and robust job boards.
• Invest in ongoing skill development and continuing education, both for immediate value and future earning potential.
• Seek to understand and negotiate high-impact but less obvious benefits (malpractice coverage, admin time, professional memberships).

NEGOTIATION TIPS:
• Always research 2–3 sources before setting negotiation targets.
• Never accept the first offer—counter with evidence.
• Stay current: revisit these resources annually for updated benchmarks.

1. SALARY AND COMPENSATION DATA
   • Bureau of Labor Statistics (BLS): https://www.bls.gov/ooh/healthcare/nurse-anesthetists-nurse-midwives-and-nurse-practitioners.htm
   • AANP Salary Survey Highlights: https://www.aanp.org/practice/practice-related-research
   • Medscape Nurse Practitioner Compensation Report: https://www.medscape.com/slideshow/2023-compensation-nurse-practitioner-6016348
   • Glassdoor NP Salaries: https://www.glassdoor.com/Salaries/nurse-practitioner-salary-SRCH_KO0,19.htm
   • Salary.com NP Salary Data: https://www.salary.com/research/healthcare/nurse-practitioner-salary

2. BENEFITS NEGOTIATION TIPS & SAMPLE CHECKLISTS
   • Nurse.org: Nurse Practitioner Contract Negotiation: https://nurse.org/articles/nurse-practitioner-salary-negotiation/
   • ANA Negotiate Your Best Salary Guide: https://www.nursingworld.org/practice-policy/workforce/compensation/
   • AANP: Resources for Contract Negotiation: https://www.aanp.org/practice/practice-related-research
   • Nurse Practitioners in Business: Negotiation Series: https://npbusiness.org/
   • MGMA: Provider Compensation Checklist: https://www.mgma.com/

3. QUICK GUIDES, BOOKLETS & PUBLICATIONS
   • The Ultimate NP Job Search Guide – Nurse.org: https://nurse.org/articles/nurse-practitioner-job-search-guide/
   • JAANP: Practice Briefs: https://www.jaanp.org/
   • Medscape NP Compensation Key Takeaways: https://www.medscape.com/slideshow/2023-compensation-nurse-practitioner-6016348
   • Nurse Practitioner Contract Review Checklist: https://nurse.org/articles/nurse-practitioner-contract-checklist/
   • ANA Short Guides and Webinars: https://www.nursingworld.org/continuing-education/

4. AUDIO, PODCASTS & VIDEO RESOURCES
   • AANP Podcast: NP Pulse: https://www.aanp.org/news-feed/podcast
   • The Nurse Practitioner Money Show: https://www.np-money.com/
   • Nursing.com: Salary & Interview Video Series: https://nursing.com/
   • The Curbsiders Podcast: https://thecurbsiders.com/

5. PROFESSIONAL GROWTH & CONTINUING EDUCATION
   • AANP Education: https://www.aanp.org/education
   • ANCC Continuing Education: https://www.nursingworld.org/ancc/
   • LinkedIn Learning: Negotiation Courses: https://www.linkedin.com/learning/

Generated by CompSherpa.ai - Your AI-powered salary negotiation coach 🦬
    `
    
    const blob = new Blob([resourceContent], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = 'CompSherpa_Resource_Library.txt'
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  const handleSuggestionSubmit = async (e) => {
    e.preventDefault()
    setSubmitted(true)
    
    // Here you would typically send to your API
    console.log('Resource suggestion submitted:', suggestionForm)
    
    // Reset form after 3 seconds
    setTimeout(() => {
      setSuggestionForm({
        name: '',
        email: '',
        resourceName: '',
        resourceUrl: '',
        description: '',
        category: ''
      })
      setSubmitted(false)
    }, 3000)
  }

  const handleInputChange = (e) => {
    const { name, value } = e.target
    setSuggestionForm(prev => ({
      ...prev,
      [name]: value
    }))
  }

  if (!user) {
    return <div>Loading...</div>
  }

  return (
    <main className="min-h-screen bg-gradient-to-br from-blue-50 to-indigo-50">
      {/* Print Styles */}
      <style jsx global>{`
        @media print {
          nav, .no-print { display: none !important; }
          body { background: white !important; }
          .print-friendly { 
            background: white !important; 
            box-shadow: none !important;
            border-radius: 0 !important;
            margin: 0 !important;
            padding: 20px !important;
          }
          .page-break { page-break-before: always; }
          .avoid-break { page-break-inside: avoid; }
          a { color: black !important; text-decoration: underline !important; }
        }
      `}</style>

      {/* Navigation Bar */}
      <nav className="bg-white shadow-md sticky top-0 z-50 no-print">
        <div className="max-w-6xl mx-auto px-4 py-3 flex justify-between items-center">
          <div className="flex items-center gap-2">
            <img src="/icon.svg" alt="CompSherpa" className="w-8 h-8" />
            <span className="text-xl font-bold text-blue-600">CompSherpa</span>
          </div>
          <div className="flex gap-4">
            <button
              onClick={() => router.push('/dashboard')}
              className="text-gray-600 hover:text-blue-600"
            >
              Dashboard
            </button>
            <button
              onClick={() => router.push('/checklist')}
              className="text-gray-600 hover:text-blue-600"
            >
              Negotiation Checklist
            </button>
            <button
              onClick={() => router.push('/deliveries')}
              className="text-gray-600 hover:text-blue-600"
            >
              Deliveries
            </button>
            <button
              onClick={() => router.push('/profile')}
              className="text-gray-600 hover:text-blue-600"
            >
              Profile
            </button>
          </div>
        </div>
      </nav>

      <div className="max-w-6xl mx-auto p-8">
        {/* Header */}
        <div className="bg-white rounded-2xl shadow-xl p-8 mb-6 print-friendly">
          <div className="flex justify-between items-start">
            <div>
              <h1 className="text-3xl font-bold mb-2">Resource Library 📚</h1>
              <p className="text-gray-600">Comprehensive job negotiation resources for Nurse Practitioners & Medical Professionals</p>
            </div>
            <div className="flex gap-2 no-print">
              <button
                onClick={handlePrint}
                className="px-4 py-2 bg-blue-500 text-white rounded-lg hover:bg-blue-600 transition"
              >
                Print
              </button>
              <button
                onClick={handleDownload}
                className="px-4 py-2 bg-green-500 text-white rounded-lg hover:bg-green-600 transition"
              >
                Download
              </button>
            </div>
          </div>
        </div>

        {/* Quick Tips Section */}
        <div className="bg-gradient-to-r from-blue-50 to-indigo-50 rounded-2xl p-8 mb-6 print-friendly">
          <h2 className="text-2xl font-bold mb-4 text-blue-800">Quick Tips From Source Library</h2>
          <p className="text-gray-700 mb-4">
            For nurse practitioners and medical job seekers, maximizing career success goes far beyond base salary. The most effective professionals:
          </p>
          <ul className="space-y-2 text-gray-700 mb-6">
            <li>• Use trusted sources to benchmark compensation and understand regional/specialty trends.</li>
            <li>• Proactively prepare for negotiations, focusing on total compensation—not just salary. This includes bonuses, paid leave, CME, retirement, flexible scheduling, and student loan support.</li>
            <li>• Rely on peer-reviewed guides, podcasts, and real contract checklists to avoid overlooked pitfalls.</li>
            <li>• Join professional organizations for member-exclusive salary data, toolkits, and robust job boards.</li>
            <li>• Invest in ongoing skill development and continuing education, both for immediate value and future earning potential.</li>
            <li>• Seek to understand and negotiate high-impact but less obvious benefits (malpractice coverage, admin time, professional memberships).</li>
          </ul>
          
          <div className="bg-blue-100 border-l-4 border-blue-500 p-4 rounded">
            <h3 className="font-bold text-blue-800 mb-2">Negotiation Tips:</h3>
            <ul className="text-blue-700 space-y-1">
              <li>• Always research 2–3 sources before setting negotiation targets.</li>
              <li>• Never accept the first offer—counter with evidence.</li>
              <li>• Stay current: revisit these resources annually for updated benchmarks.</li>
            </ul>
          </div>
        </div>

        {/* Resource Sections */}
        <div className="space-y-6">
          {/* Section 1: Salary and Compensation Data */}
          <div className="bg-white rounded-2xl shadow-xl p-8 print-friendly avoid-break">
            <h2 className="text-2xl font-bold mb-6 text-blue-600">1. Salary and Compensation Data</h2>
            <div className="overflow-x-auto">
              <table className="w-full border-collapse">
                <thead>
                  <tr className="bg-gray-50">
                    <th className="border border-gray-300 px-4 py-3 text-left font-semibold">Resource</th>
                    <th className="border border-gray-300 px-4 py-3 text-left font-semibold">Description</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td className="border border-gray-300 px-4 py-3">
                      <a href="https://www.bls.gov/ooh/healthcare/nurse-anesthetists-nurse-midwives-and-nurse-practitioners.htm" target="_blank" rel="noopener noreferrer" className="text-blue-600 hover:text-blue-800 font-medium">
                        Bureau of Labor Statistics (BLS)
                      </a>
                    </td>
                    <td className="border border-gray-300 px-4 py-3">Authoritative source for NP salary data by geography and setting, plus job growth projections.</td>
                  </tr>
                  <tr>
                    <td className="border border-gray-300 px-4 py-3">
                      <a href="https://www.aanp.org/practice/practice-related-research" target="_blank" rel="noopener noreferrer" className="text-blue-600 hover:text-blue-800 font-medium">
                        AANP Salary Survey Highlights
                      </a>
                    </td>
                    <td className="border border-gray-300 px-4 py-3">Annual, NP-specific compensation survey available to AANP members; summary data often public.</td>
                  </tr>
                  <tr>
                    <td className="border border-gray-300 px-4 py-3">
                      <a href="https://www.medscape.com/slideshow/2023-compensation-nurse-practitioner-6016348" target="_blank" rel="noopener noreferrer" className="text-blue-600 hover:text-blue-800 font-medium">
                        Medscape Nurse Practitioner Compensation Report
                      </a>
                    </td>
                    <td className="border border-gray-300 px-4 py-3">Annual survey of NP salary, bonuses, and benefits by specialty, region, and setting.</td>
                  </tr>
                  <tr>
                    <td className="border border-gray-300 px-4 py-3">
                      <a href="https://www.glassdoor.com/Salaries/nurse-practitioner-salary-SRCH_KO0,19.htm" target="_blank" rel="noopener noreferrer" className="text-blue-600 hover:text-blue-800 font-medium">
                        Glassdoor NP Salaries
                      </a>
                    </td>
                    <td className="border border-gray-300 px-4 py-3">Aggregated salary data from verified NP employees, with benefit snapshots and interview questions.</td>
                  </tr>
                  <tr>
                    <td className="border border-gray-300 px-4 py-3">
                      <a href="https://www.salary.com/research/healthcare/nurse-practitioner-salary" target="_blank" rel="noopener noreferrer" className="text-blue-600 hover:text-blue-800 font-medium">
                        Salary.com NP Salary Data
                      </a>
                    </td>
                    <td className="border border-gray-300 px-4 py-3">Customizable salary calculator with detailed pay breakdowns and location adjustments.</td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>

          {/* Section 2: Benefits Negotiation Tips */}
          <div className="bg-white rounded-2xl shadow-xl p-8 print-friendly page-break">
            <h2 className="text-2xl font-bold mb-6 text-green-600">2. Benefits Negotiation Tips & Sample Checklists</h2>
            <div className="overflow-x-auto">
              <table className="w-full border-collapse">
                <thead>
                  <tr className="bg-gray-50">
                    <th className="border border-gray-300 px-4 py-3 text-left font-semibold">Resource</th>
                    <th className="border border-gray-300 px-4 py-3 text-left font-semibold">Description</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td className="border border-gray-300 px-4 py-3">
                      <a href="https://nurse.org/articles/nurse-practitioner-salary-negotiation/" target="_blank" rel="noopener noreferrer" className="text-blue-600 hover:text-blue-800 font-medium">
                        Nurse.org: Nurse Practitioner Contract Negotiation
                      </a>
                    </td>
                    <td className="border border-gray-300 px-4 py-3">Practical tips on negotiating pay, benefits, and job terms with real-world examples.</td>
                  </tr>
                  <tr>
                    <td className="border border-gray-300 px-4 py-3">
                      <a href="https://www.nursingworld.org/practice-policy/workforce/compensation/" target="_blank" rel="noopener noreferrer" className="text-blue-600 hover:text-blue-800 font-medium">
                        ANA Negotiate Your Best Salary Guide
                      </a>
                    </td>
                    <td className="border border-gray-300 px-4 py-3">Free downloadable guide from the American Nurses Association on maximizing compensation.</td>
                  </tr>
                  <tr>
                    <td className="border border-gray-300 px-4 py-3">
                      <a href="https://www.aanp.org/practice/practice-related-research" target="_blank" rel="noopener noreferrer" className="text-blue-600 hover:text-blue-800 font-medium">
                        AANP: Resources for Contract Negotiation
                      </a>
                    </td>
                    <td className="border border-gray-300 px-4 py-3">Short guides, checklists, and webinar links on NP contract and compensation negotiation.</td>
                  </tr>
                  <tr>
                    <td className="border border-gray-300 px-4 py-3">
                      <a href="https://npbusiness.org/" target="_blank" rel="noopener noreferrer" className="text-blue-600 hover:text-blue-800 font-medium">
                        Nurse Practitioners in Business: Negotiation Series
                      </a>
                    </td>
                    <td className="border border-gray-300 px-4 py-3">Blog series by experienced NPs on negotiation strategy and benefits prioritization.</td>
                  </tr>
                  <tr>
                    <td className="border border-gray-300 px-4 py-3">
                      <a href="https://www.mgma.com/" target="_blank" rel="noopener noreferrer" className="text-blue-600 hover:text-blue-800 font-medium">
                        MGMA: Provider Compensation Checklist
                      </a>
                    </td>
                    <td className="border border-gray-300 px-4 py-3">General medical provider checklist for contract review and negotiation.</td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>

          {/* Section 3: Quick Guides */}
          <div className="bg-white rounded-2xl shadow-xl p-8 print-friendly page-break">
            <h2 className="text-2xl font-bold mb-6 text-purple-600">3. Quick Guides, Booklets & Publications</h2>
            <div className="overflow-x-auto">
              <table className="w-full border-collapse">
                <thead>
                  <tr className="bg-gray-50">
                    <th className="border border-gray-300 px-4 py-3 text-left font-semibold">Resource</th>
                    <th className="border border-gray-300 px-4 py-3 text-left font-semibold">Description</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td className="border border-gray-300 px-4 py-3">
                      <a href="https://nurse.org/articles/nurse-practitioner-job-search-guide/" target="_blank" rel="noopener noreferrer" className="text-blue-600 hover:text-blue-800 font-medium">
                        The Ultimate NP Job Search Guide – Nurse.org
                      </a>
                    </td>
                    <td className="border border-gray-300 px-4 py-3">Concise e-booklet covering resumes, interviews, negotiations, and early career pitfalls.</td>
                  </tr>
                  <tr>
                    <td className="border border-gray-300 px-4 py-3">
                      <a href="https://www.jaanp.org/" target="_blank" rel="noopener noreferrer" className="text-blue-600 hover:text-blue-800 font-medium">
                        JAANP: Practice Briefs
                      </a>
                    </td>
                    <td className="border border-gray-300 px-4 py-3">Peer-reviewed NP articles—use keyword "negotiation" for relevant briefs.</td>
                  </tr>
                  <tr>
                    <td className="border border-gray-300 px-4 py-3">
                      <a href="https://www.medscape.com/slideshow/2023-compensation-nurse-practitioner-6016348" target="_blank" rel="noopener noreferrer" className="text-blue-600 hover:text-blue-800 font-medium">
                        Medscape NP Compensation Key Takeaways
                      </a>
                    </td>
                    <td className="border border-gray-300 px-4 py-3">Visual summary slides breaking down compensation highlights.</td>
                  </tr>
                  <tr>
                    <td className="border border-gray-300 px-4 py-3">
                      <a href="https://nurse.org/articles/nurse-practitioner-contract-checklist/" target="_blank" rel="noopener noreferrer" className="text-blue-600 hover:text-blue-800 font-medium">
                        Nurse Practitioner Contract Review Checklist
                      </a>
                    </td>
                    <td className="border border-gray-300 px-4 py-3">Simple, free checklist for reviewing NP contracts and protecting your interests.</td>
                  </tr>
                  <tr>
                    <td className="border border-gray-300 px-4 py-3">
                      <a href="https://www.nursingworld.org/continuing-education/" target="_blank" rel="noopener noreferrer" className="text-blue-600 hover:text-blue-800 font-medium">
                        ANA Short Guides and Webinars
                      </a>
                    </td>
                    <td className="border border-gray-300 px-4 py-3">Brief guides and recorded negotiation webinars (search "negotiation" in CE catalog).</td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>

          {/* Section 4: Audio & Video */}
          <div className="bg-white rounded-2xl shadow-xl p-8 print-friendly page-break">
            <h2 className="text-2xl font-bold mb-6 text-orange-600">4. Audio, Podcasts & Video Resources</h2>
            <div className="overflow-x-auto">
              <table className="w-full border-collapse">
                <thead>
                  <tr className="bg-gray-50">
                    <th className="border border-gray-300 px-4 py-3 text-left font-semibold">Resource</th>
                    <th className="border border-gray-300 px-4 py-3 text-left font-semibold">Description</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td className="border border-gray-300 px-4 py-3">
                      <a href="https://www.aanp.org/news-feed/podcast" target="_blank" rel="noopener noreferrer" className="text-blue-600 hover:text-blue-800 font-medium">
                        AANP Podcast: NP Pulse
                      </a>
                    </td>
                    <td className="border border-gray-300 px-4 py-3">Episodes on negotiation, compensation, benefits, and NP career insights.</td>
                  </tr>
                  <tr>
                    <td className="border border-gray-300 px-4 py-3">
                      <a href="https://www.np-money.com/" target="_blank" rel="noopener noreferrer" className="text-blue-600 hover:text-blue-800 font-medium">
                        The Nurse Practitioner Money Show
                      </a>
                    </td>
                    <td className="border border-gray-300 px-4 py-3">Focused on personal finance, salaries, and benefits for working NPs.</td>
                  </tr>
                  <tr>
                    <td className="border border-gray-300 px-4 py-3">
                      <a href="https://nursing.com/" target="_blank" rel="noopener noreferrer" className="text-blue-600 hover:text-blue-800 font-medium">
                        Nursing.com: Salary & Interview Video Series
                      </a>
                    </td>
                    <td className="border border-gray-300 px-4 py-3">Bite-size video tips on salary negotiation and job interviews.</td>
                  </tr>
                  <tr>
                    <td className="border border-gray-300 px-4 py-3">
                      <a href="https://thecurbsiders.com/" target="_blank" rel="noopener noreferrer" className="text-blue-600 hover:text-blue-800 font-medium">
                        The Curbsiders Podcast
                      </a>
                    </td>
                    <td className="border border-gray-300 px-4 py-3">Broader medical focus, often includes professional development and career strategy episodes.</td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>

          {/* Section 5: Professional Growth */}
          <div className="bg-white rounded-2xl shadow-xl p-8 print-friendly page-break">
            <h2 className="text-2xl font-bold mb-6 text-red-600">5. Professional Growth & Continuing Education</h2>
            <div className="overflow-x-auto">
              <table className="w-full border-collapse">
                <thead>
                  <tr className="bg-gray-50">
                    <th className="border border-gray-300 px-4 py-3 text-left font-semibold">Resource</th>
                    <th className="border border-gray-300 px-4 py-3 text-left font-semibold">Description</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td className="border border-gray-300 px-4 py-3">
                      <a href="https://www.aanp.org/education" target="_blank" rel="noopener noreferrer" className="text-blue-600 hover:text-blue-800 font-medium">
                        AANP Education
                      </a>
                    </td>
                    <td className="border border-gray-300 px-4 py-3">Member and non-member CE resources, including negotiation, legal, and career topics.</td>
                  </tr>
                  <tr>
                    <td className="border border-gray-300 px-4 py-3">
                      <a href="https://www.nursingworld.org/ancc/" target="_blank" rel="noopener noreferrer" className="text-blue-600 hover:text-blue-800 font-medium">
                        ANCC Continuing Education
                      </a>
                    </td>
                    <td className="border border-gray-300 px-4 py-3">Accredited online courses, including work-life balance and salary negotiation.</td>
                  </tr>
                  <tr>
                    <td className="border border-gray-300 px-4 py-3">
                      <a href="https://www.linkedin.com/learning/" target="_blank" rel="noopener noreferrer" className="text-blue-600 hover:text-blue-800 font-medium">
                        LinkedIn Learning: Negotiation Courses
                      </a>
                    </td>
                    <td className="border border-gray-300 px-4 py-3">Short microlearning modules (subscription may be required).</td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
        </div>

        {/* Suggestion Form */}
        <div className="bg-white rounded-2xl shadow-xl p-8 mt-6 no-print">
          <h2 className="text-2xl font-bold mb-4">Suggest a Resource 📝</h2>
          <p className="text-gray-600 mb-6">
            We're always looking to expand our resource library! If you know of a great resource that would help other NPs with salary negotiation, job search, or career development, please share it with us.
          </p>
          
          {submitted ? (
            <div className="bg-green-50 border border-green-200 rounded-lg p-4">
              <p className="text-green-800 font-medium">Thank you for your suggestion! We'll review it and add it to our library if it fits our criteria.</p>
            </div>
          ) : (
            <form onSubmit={handleSuggestionSubmit} className="space-y-4">
              <div className="grid md:grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">Your Name</label>
                  <input
                    type="text"
                    name="name"
                    value={suggestionForm.name}
                    onChange={handleInputChange}
                    className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                    required
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">Your Email</label>
                  <input
                    type="email"
                    name="email"
                    value={suggestionForm.email}
                    onChange={handleInputChange}
                    className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                    required
                  />
                </div>
              </div>
              
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Resource Name</label>
                <input
                  type="text"
                  name="resourceName"
                  value={suggestionForm.resourceName}
                  onChange={handleInputChange}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                  placeholder="e.g., NP Salary Negotiation Guide"
                  required
                />
              </div>
              
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Resource URL</label>
                <input
                  type="url"
                  name="resourceUrl"
                  value={suggestionForm.resourceUrl}
                  onChange={handleInputChange}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                  placeholder="https://example.com/resource"
                  required
                />
              </div>
              
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Category</label>
                <select
                  name="category"
                  value={suggestionForm.category}
                  onChange={handleInputChange}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                  required
                >
                  <option value="">Select a category</option>
                  <option value="salary-data">Salary and Compensation Data</option>
                  <option value="negotiation-tips">Benefits Negotiation Tips</option>
                  <option value="guides">Quick Guides & Publications</option>
                  <option value="audio-video">Audio, Podcasts & Video</option>
                  <option value="education">Professional Growth & CE</option>
                  <option value="other">Other</option>
                </select>
              </div>
              
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Description</label>
                <textarea
                  name="description"
                  value={suggestionForm.description}
                  onChange={handleInputChange}
                  rows="3"
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                  placeholder="Brief description of what this resource offers and why it would be valuable to NPs..."
                  required
                />
              </div>
              
              <button
                type="submit"
                className="w-full bg-blue-500 text-white py-3 rounded-lg hover:bg-blue-600 transition font-semibold"
              >
                Submit Resource Suggestion
              </button>
            </form>
          )}
        </div>
      </div>
    </main>
  )
} 