'use client'

import { useRouter } from 'next/navigation'
import { useAuth } from '../../Lib/auth'

export default function Checklist() {
  const { user } = useAuth()
  const router = useRouter()

  const handlePrint = () => {
    window.print()
  }

  const handleDownload = () => {
    // Create a printable version of the checklist
    const checklistContent = `
CompSherpa Negotiation Checklist
================================

Nurse Practitioner & Medical Professional Compensation Negotiation Checklist

Use this practical checklist to guide your job offer evaluation and contract negotiation. Each section is tailored for busy nurse practitioners and healthcare professionals seeking to maximize both compensation and long-term career satisfaction.

1. SALARY & CORE COMPENSATION
   □ What is the base salary? Is it competitive for your specialty, experience, and region?
   □ Are there opportunities for annual merit, cost-of-living, or market adjustments?
   □ What is the salary review period (e.g., every 12 months)?
   □ Are bonuses available (signing, performance, productivity)? What are the criteria?
   □ How is overtime or additional shift pay (if applicable) structured?

2. BENEFITS & PERKS
   □ Health insurance: What plans are offered (medical, dental, vision)? What portion does employer cover?
   □ Retirement plan: Is there a 401(k), 403(b), or pension? What is the employer match percentage or contribution?
   □ Paid time off (PTO): How many days for vacation, sick leave, personal, CME/conference, holidays?
   □ Continuing education (CME/CE): Is there an annual allowance for CME fees, travel, and time off?
   □ Student loan repayment or tuition reimbursement: Is there employer support? What are the terms and duration?
   □ Malpractice/liability insurance: Is this fully covered, and does it include "tail" coverage?
   □ Licensing, certification, professional dues: Are these fees reimbursed?
   □ Relocation/signing bonus: Is there financial support for moving, and what are repayment clauses?

3. SCHEDULE & WORK ENVIRONMENT
   □ What is the expected work schedule (hours, days/week, call/onsite requirements)?
   □ Are there options for flexible scheduling, remote work, or telemedicine?
   □ What administrative time is allotted (charting, care coordination)?
   □ Is onboarding/training provided? What does orientation look like?
   □ What is the expected patient volume per shift?

4. CAREER DEVELOPMENT & GROWTH
   □ Are there opportunities for advancement (leadership, teaching, research, specialization)?
   □ Is there a mentorship or support network for new hires?
   □ Are performance reviews conducted regularly, and are clear goalposts set?

5. CONTRACT & LEGAL
   □ Are all compensation and benefits detailed in writing in the offer and contract?
   □ Does the contract include a non-compete or geographic restriction? Is it reasonable and negotiable?
   □ What are the termination provisions (notice period, cause, severance)?
   □ Is ownership of patient lists or intellectual property addressed?
   □ Is there a clause specifying the process for contract renewal?

6. CRITICAL RED FLAGS
   □ Vague language regarding compensation, duties, or benefits.
   □ Unreasonable non-compete or restrictive covenants.
   □ No clear process for performance improvement, review, or salary increases.
   □ Absence of standard malpractice insurance or "tail" coverage.
   □ Productivity expectations not aligned with industry standards.

TIP: Bring this checklist to interviews and offer discussions. Mark all areas provided, negotiable, or needing clarification.

Generated by CompSherpa.ai - Your AI-powered salary negotiation coach 🦬
    `
    
    const blob = new Blob([checklistContent], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = 'CompSherpa_Negotiation_Checklist.txt'
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  return (
    <main className="min-h-screen bg-gradient-to-br from-blue-50 to-indigo-50">
      {/* Print Styles */}
      <style jsx global>{`
        @media print {
          nav, .no-print { display: none !important; }
          body { background: white !important; }
          .print-friendly { 
            background: white !important; 
            box-shadow: none !important;
            border-radius: 0 !important;
            margin: 0 !important;
            padding: 20px !important;
          }
          .page-break { page-break-before: always; }
          .avoid-break { page-break-inside: avoid; }
        }
      `}</style>

      {/* Navigation Bar */}
      <nav className="bg-white shadow-md sticky top-0 z-50 no-print">
        <div className="max-w-6xl mx-auto px-4 py-3 flex justify-between items-center">
          <div className="text-xl font-bold text-blue-600">
            <span className="text-xl font-bold text-blue-600">CompSherpa</span>
          </div>
          <div className="flex gap-4">
            <button
              onClick={() => router.push('/dashboard')}
              className="text-gray-600 hover:text-blue-600"
            >
              Dashboard
            </button>
            <div className="text-blue-600 font-medium">Negotiation Checklist</div>
            <button
              onClick={() => router.push('/resources')}
              className="text-gray-600 hover:text-blue-600"
            >
              Resource Library
            </button>
            <button
              onClick={() => router.push('/profile')}
              className="text-gray-600 hover:text-blue-600"
            >
              Profile
            </button>
          </div>
        </div>
      </nav>

      <div className="max-w-4xl mx-auto p-8">
        {/* Header */}
        <div className="bg-white rounded-2xl shadow-xl p-8 mb-6 print-friendly">
          <div className="flex justify-between items-start">
            <div>
              <h1 className="text-3xl font-bold mb-2">Negotiation Checklist 📋</h1>
              <p className="text-gray-600">Your comprehensive guide to successful salary negotiations</p>
            </div>
            <div className="flex gap-2 no-print">
              <button
                onClick={handlePrint}
                className="px-4 py-2 bg-blue-500 text-white rounded-lg hover:bg-blue-600 transition"
              >
                Print
              </button>
              <button
                onClick={handleDownload}
                className="px-4 py-2 bg-green-500 text-white rounded-lg hover:bg-green-600 transition"
              >
                Download
              </button>
            </div>
          </div>
        </div>

        {/* Introduction */}
        <div className="bg-white rounded-2xl shadow-xl p-8 mb-6 print-friendly">
          <p className="text-lg text-gray-700 leading-relaxed">
            CompSherpa and our partners have put together a helpful negotiation checklist below for you to use in the interview and negotiation process. There are additional sources below if you would like to do more of your own research.
          </p>
        </div>

        {/* Main Checklist */}
        <div className="bg-white rounded-2xl shadow-xl p-8 mb-6 print-friendly avoid-break">
          <h2 className="text-2xl font-bold mb-6 text-center">Nurse Practitioner & Medical Professional Compensation Negotiation Checklist</h2>
          <p className="text-gray-600 mb-8 text-center">
            Use this practical checklist to guide your job offer evaluation and contract negotiation. Each section is tailored for busy nurse practitioners and healthcare professionals seeking to maximize both compensation and long-term career satisfaction.
          </p>

          <div className="space-y-8">
            {/* Section 1 */}
            <div className="border-l-4 border-blue-500 pl-6">
              <h3 className="text-xl font-bold mb-4 text-blue-600">1. Salary & Core Compensation</h3>
              <ul className="space-y-2 text-gray-700">
                <li>• What is the base salary? Is it competitive for your specialty, experience, and region?</li>
                <li>• Are there opportunities for annual merit, cost-of-living, or market adjustments?</li>
                <li>• What is the salary review period (e.g., every 12 months)?</li>
                <li>• Are bonuses available (signing, performance, productivity)? What are the criteria?</li>
                <li>• How is overtime or additional shift pay (if applicable) structured?</li>
              </ul>
            </div>

            {/* Section 2 */}
            <div className="border-l-4 border-green-500 pl-6">
              <h3 className="text-xl font-bold mb-4 text-green-600">2. Benefits & Perks</h3>
              <ul className="space-y-2 text-gray-700">
                <li>• Health insurance: What plans are offered (medical, dental, vision)? What portion does employer cover?</li>
                <li>• Retirement plan: Is there a 401(k), 403(b), or pension? What is the employer match percentage or contribution?</li>
                <li>• Paid time off (PTO): How many days for vacation, sick leave, personal, CME/conference, holidays?</li>
                <li>• Continuing education (CME/CE): Is there an annual allowance for CME fees, travel, and time off?</li>
                <li>• Student loan repayment or tuition reimbursement: Is there employer support? What are the terms and duration?</li>
                <li>• Malpractice/liability insurance: Is this fully covered, and does it include "tail" coverage?</li>
                <li>• Licensing, certification, professional dues: Are these fees reimbursed?</li>
                <li>• Relocation/signing bonus: Is there financial support for moving, and what are repayment clauses?</li>
              </ul>
            </div>

            {/* Section 3 */}
            <div className="border-l-4 border-purple-500 pl-6">
              <h3 className="text-xl font-bold mb-4 text-purple-600">3. Schedule & Work Environment</h3>
              <ul className="space-y-2 text-gray-700">
                <li>• What is the expected work schedule (hours, days/week, call/onsite requirements)?</li>
                <li>• Are there options for flexible scheduling, remote work, or telemedicine?</li>
                <li>• What administrative time is allotted (charting, care coordination)?</li>
                <li>• Is onboarding/training provided? What does orientation look like?</li>
                <li>• What is the expected patient volume per shift?</li>
              </ul>
            </div>

            {/* Section 4 */}
            <div className="border-l-4 border-orange-500 pl-6">
              <h3 className="text-xl font-bold mb-4 text-orange-600">4. Career Development & Growth</h3>
              <ul className="space-y-2 text-gray-700">
                <li>• Are there opportunities for advancement (leadership, teaching, research, specialization)?</li>
                <li>• Is there a mentorship or support network for new hires?</li>
                <li>• Are performance reviews conducted regularly, and are clear goalposts set?</li>
              </ul>
            </div>

            {/* Section 5 */}
            <div className="border-l-4 border-red-500 pl-6">
              <h3 className="text-xl font-bold mb-4 text-red-600">5. Contract & Legal</h3>
              <ul className="space-y-2 text-gray-700">
                <li>• Are all compensation and benefits detailed in writing in the offer and contract?</li>
                <li>• Does the contract include a non-compete or geographic restriction? Is it reasonable and negotiable?</li>
                <li>• What are the termination provisions (notice period, cause, severance)?</li>
                <li>• Is ownership of patient lists or intellectual property addressed?</li>
                <li>• Is there a clause specifying the process for contract renewal?</li>
              </ul>
            </div>

            {/* Section 6 */}
            <div className="border-l-4 border-yellow-500 pl-6">
              <h3 className="text-xl font-bold mb-4 text-yellow-600">6. Critical Red Flags</h3>
              <ul className="space-y-2 text-gray-700">
                <li>• Vague language regarding compensation, duties, or benefits.</li>
                <li>• Unreasonable non-compete or restrictive covenants.</li>
                <li>• No clear process for performance improvement, review, or salary increases.</li>
                <li>• Absence of standard malpractice insurance or "tail" coverage.</li>
                <li>• Productivity expectations not aligned with industry standards.</li>
              </ul>
            </div>
          </div>

          {/* Tip */}
          <div className="mt-8 p-6 bg-blue-50 rounded-lg border-l-4 border-blue-500 avoid-break">
            <h4 className="font-bold text-blue-800 mb-2">💡 Tip:</h4>
            <p className="text-blue-700">
              Bring this checklist to interviews and offer discussions. Mark all areas provided, negotiable, or needing clarification.
            </p>
          </div>
        </div>

        {/* Resources */}
        <div className="bg-white rounded-2xl shadow-xl p-8 print-friendly page-break">
          <h3 className="text-2xl font-bold mb-6">Helpful Resources</h3>
          <div className="grid md:grid-cols-2 gap-6">
            <div className="space-y-4">
              <a 
                href="https://www.bls.gov/ooh/healthcare/nurse-anesthetists-nurse-midwives-and-nurse-practitioners.htm" 
                target="_blank" 
                rel="noopener noreferrer"
                className="block p-4 border border-gray-200 rounded-lg hover:border-blue-300 hover:bg-blue-50 transition"
              >
                <h4 className="font-semibold text-blue-600 mb-1">BLS Occupational Outlook Handbook – NP</h4>
                <p className="text-sm text-gray-600">Official government data on NP employment and compensation trends</p>
              </a>
              
              <a 
                href="https://www.medscape.com/slideshow/2023-compensation-nurse-practitioner-6016348" 
                target="_blank" 
                rel="noopener noreferrer"
                className="block p-4 border border-gray-200 rounded-lg hover:border-blue-300 hover:bg-blue-50 transition"
              >
                <h4 className="font-semibold text-blue-600 mb-1">Medscape NP Compensation Report</h4>
                <p className="text-sm text-gray-600">Annual survey of NP compensation across specialties and regions</p>
              </a>
            </div>
            
            <div className="space-y-4">
              <a 
                href="https://nurse.org/articles/nurse-practitioner-salary-negotiation/" 
                target="_blank" 
                rel="noopener noreferrer"
                className="block p-4 border border-gray-200 rounded-lg hover:border-blue-300 hover:bg-blue-50 transition"
              >
                <h4 className="font-semibold text-blue-600 mb-1">Nurse.org Negotiation Guide</h4>
                <p className="text-sm text-gray-600">Comprehensive guide to NP salary negotiation strategies</p>
              </a>
              
              <a 
                href="https://www.nursingworld.org/practice-policy/workforce/compensation/" 
                target="_blank" 
                rel="noopener noreferrer"
                className="block p-4 border border-gray-200 rounded-lg hover:border-blue-300 hover:bg-blue-50 transition"
              >
                <h4 className="font-semibold text-blue-600 mb-1">ANA Salary Negotiation Guide</h4>
                <p className="text-sm text-gray-600">American Nurses Association resources for compensation negotiation</p>
              </a>
            </div>
          </div>
          
          <div className="mt-6 p-4 bg-green-50 rounded-lg border-l-4 border-green-500">
            <p className="text-green-800 font-medium">
              This checklist ensures you consider every critical aspect of your job offer and negotiate for a well-rounded, future-proof compensation package.
            </p>
          </div>
        </div>
      </div>
    </main>
  )
} 